-- SPDX-License-Identifier: GPL-3.0-only
-- Copyright (C) 2026 AlbiDR

-- 1. CLINICAL SCHEMAS (CleanStack Layer Isolation)
CREATE SCHEMA IF NOT EXISTS substrate; -- L0: Raw Inbound Truth
CREATE SCHEMA IF NOT EXISTS drivers;   -- L2: Domain Molecules/Relational
CREATE SCHEMA IF NOT EXISTS features;  -- L3: Business Silos (Views)
CREATE SCHEMA IF NOT EXISTS system;    -- L5: Internal Orchestration

-- 2. EXTENSIONS (The Engine)
CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";
CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE EXTENSION IF NOT EXISTS pg_net;
CREATE EXTENSION IF NOT EXISTS moddatetime;

-- 3. SUBSTRATE (Layer 0: Raw Ingestion)
CREATE TABLE IF NOT EXISTS substrate.raw_clan_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payload JSONB NOT NULL,
    ingested_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS substrate.raw_clan_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payload JSONB NOT NULL,
    ingested_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. DRIVERS (Layer 2: Authoritative Domain)
CREATE TABLE IF NOT EXISTS drivers.clans (
    tag TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    badge_id INT,
    member_count INT,
    last_ingested_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS drivers.members (
    tag TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    role TEXT,
    exp_level INT,
    first_seen_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_seen_at TIMESTAMP WITH TIME ZONE,
    is_active BOOLEAN DEFAULT TRUE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS drivers.member_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_tag TEXT REFERENCES drivers.members(tag) ON DELETE CASCADE,
    trophies INT,
    donations INT,
    donations_received INT,
    last_seen TIMESTAMP WITH TIME ZONE,
    snapshot_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- 5. SHREDDING LOGIC (Automatic Fan-out)
-- A. Clan Profile Shredder
CREATE OR REPLACE FUNCTION substrate.shred_clan_profile() 
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO drivers.clans (tag, name, description, badge_id, member_count, last_ingested_at)
    VALUES (
        NEW.payload->>'tag',
        NEW.payload->>'name',
        NEW.payload->>'description',
        (NEW.payload->>'badgeId')::INT,
        (NEW.payload->>'members')::INT,
        NEW.ingested_at
    )
    ON CONFLICT (tag) DO UPDATE SET
        name = EXCLUDED.name,
        description = EXCLUDED.description,
        badge_id = EXCLUDED.badge_id,
        member_count = EXCLUDED.member_count,
        last_ingested_at = EXCLUDED.last_ingested_at;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- B. Roster Ingestion Shredder (The Fan-out)
CREATE OR REPLACE FUNCTION substrate.shred_member_list() 
RETURNS TRIGGER AS $$
DECLARE
    member_record JSONB;
BEGIN
    FOR member_record IN SELECT * FROM jsonb_array_elements(NEW.payload->'items')
    LOOP
        INSERT INTO drivers.members (tag, name, role, exp_level, last_seen_at, updated_at)
        VALUES (
            member_record->>'tag',
            member_record->>'name',
            member_record->>'role',
            (member_record->>'expLevel')::INT,
            (member_record->>'lastSeen')::TIMESTAMP WITH TIME ZONE,
            NEW.ingested_at
        )
        ON CONFLICT (tag) DO UPDATE SET
            name = EXCLUDED.name, role = EXCLUDED.role, exp_level = EXCLUDED.exp_level,
            last_seen_at = EXCLUDED.last_seen_at, updated_at = EXCLUDED.updated_at, is_active = TRUE;

        INSERT INTO drivers.member_snapshots (member_tag, trophies, donations, donations_received, last_seen, snapshot_at)
        VALUES (
            member_record->>'tag',
            (member_record->>'trophies')::INT,
            (member_record->>'donations')::INT,
            (member_record->>'donationsReceived')::INT,
            (member_record->>'lastSeen')::TIMESTAMP WITH TIME ZONE,
            NEW.ingested_at
        );
    END LOOP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 6. TRIGGERS (Automated Activation)
CREATE TRIGGER on_clan_profile_ingested AFTER INSERT ON substrate.raw_clan_profile FOR EACH ROW EXECUTE FUNCTION substrate.shred_clan_profile();
CREATE TRIGGER on_roster_ingested AFTER INSERT ON substrate.raw_clan_members FOR EACH ROW EXECUTE FUNCTION substrate.shred_member_list();

-- 7. ORCHESTRATION (The Watchdog Heartbeat)
SELECT cron.schedule('ingest-royale-heartbeat', '30 * * * *', $$
    SELECT net.http_post(
        url := 'https://hucktamloykszinwbtuh.supabase.co/functions/v1/ingest-royale-data',
        headers := '{"Content-Type": "application/json"}'::jsonb
    )
$$);
