-- SPDX-License-Identifier: GPL-3.0-only
-- Copyright (C) 2026 AlbiDR

-- =============================================================================
-- Migration: 20260801010000_recruit_win_rate_backfill.sql
--
-- Forces a rescan pass for every ACTIVE, BENCHED, and QUEUE recruit whose
-- win_rate is still at the default 0.0 despite having a non-zero
-- raw_potential_score. This is the primary fix for recruits displaying an
-- invalid 0% win rate on the Recruit Card and contributing a corrupt zero
-- to the RPeS ranking normalization.
--
-- Root causes (documented in win-rate-recalculation-SSOT.md Section 2.3):
--
--   Sub-cause A -- Pre-migration rows:
--   Migration 20260727000000_rpos_rescan_backfill.sql backdated last_scan for
--   rows with win_rate = 0, but some were re-profiled after the formula
--   migration and had win_rate legitimately set to 0 (zero-battle profile).
--   Those rows pass the win_rate = 0 filter again. The raw_potential_score > 0
--   guard in this migration (see Decision D4 in the SSOT) distinguishes
--   between a genuinely zero-battle player (raw_potential_score = 0, nothing
--   to rescan) and a player whose battle history was simply never fetched
--   (raw_potential_score > 0 -- they have trophies/donations, so they are
--   active players and zero battles is implausible).
--
--   Sub-cause B -- SHADOW leads:
--   deep-depth.ts inserts shadow leads via sync_recruits with no win_rate in
--   the payload. public.sync_recruits() applies COALESCE(..., 0.0), so every
--   shadow lead lands with win_rate = 0 regardless of their actual CR record.
--   Shadow leads are not re-profiled until last_scan is older than 48 hours,
--   since they are inserted with last_scan = NOW(). This migration forces
--   their immediate re-profiling via the same last_scan backdate.
--
-- Fix strategy:
-- Backdate last_scan past the 48-hour staleness threshold used by
-- get_stale_recruits. The existing rescan stage (runRescan in rescan.ts) picks
-- these rows up on its next cycle, fetches live CR API profiles, computes
-- win_rate via calculateWeightedWinRate(), and persists the result via
-- sync_recruits. No scoring logic lives here -- the Edge Function remains the
-- single source of truth for the formula. This is a scheduling nudge only,
-- identical in mechanism to 20260727000000_rpos_rescan_backfill.sql.
--
-- Batching: get_stale_recruits caps to RESCAN_BATCH_LIMIT (250 rows per run).
-- The headhunter-scanner runs every 30 minutes via pg_cron. Multiple cycles
-- drain the queue automatically. At 250 rows per cycle, a corpus of 1000
-- affected recruits converges within 2 hours.
--
-- Scope:
-- Targets only status IN ('ACTIVE', 'BENCHED', 'QUEUE'). ARCHIVED and INVITED
-- recruits are excluded -- they are outside the active scoring corpus.
-- Recruits in drivers.recruit_blacklist are excluded -- get_stale_recruits
-- does not cover that table, and blacklisted entries are absent from
-- headhunter_view. Their win_rate snapshot issue is addressed separately
-- in 20260801020000_blacklist_win_rate_snapshot.sql (Phase 4).
--
-- Guard: raw_potential_score > 0
-- A recruit with raw_potential_score = 0 has no trophies AND no donations
-- AND no battle history: either a bot account or a newly created account that
-- somehow passed the trophy filter. Re-scanning them against the live API
-- would return the same zero result and waste Royale API quota. They are
-- deliberately excluded from this backfill.
--
-- Verification (run after 2-4 headhunter-scanner cron cycles, ~2 hours):
--   SELECT count(*) FROM drivers.recruits
--    WHERE status IN ('ACTIVE', 'BENCHED', 'QUEUE')
--      AND win_rate = 0
--      AND raw_potential_score > 0;
-- Expected: converges toward 0. Residual rows are players whose live CR API
-- profile genuinely returns battleCount = 0 (new accounts, bot accounts that
-- passed the score filter via trophies/donations alone).
-- =============================================================================

UPDATE drivers.recruits
   SET last_scan = NOW() - INTERVAL '49 hours'
 WHERE status IN ('ACTIVE', 'BENCHED', 'QUEUE')
   AND win_rate = 0
   AND raw_potential_score > 0;
