-- SPDX-License-Identifier: GPL-3.0-only
-- Copyright (C) 2026 AlbiDR

/*
============================================================================
CONSOLIDATED BACKEND SUBSTRATE — THE CLINICAL RESET
----------------------------------------------------------------------------
This migration resets the procedural logic to the "Clinical" standard.
It unifies all previous hotfixes into a Single Source of Truth for the 
Clash-Manager backend.

L0: Substrate (Ingestion Buffer)
L2: Drivers (Relational SSoT)
L3: Features (Scoring & Presentation)
============================================================================
*/

-- -------------------------------------------------------------------------
-- I. NAMESPACE INITIALIZATION
-- -------------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS substrate; -- L0
CREATE SCHEMA IF NOT EXISTS drivers;   -- L2
CREATE SCHEMA IF NOT EXISTS features;  -- L3

-- -------------------------------------------------------------------------
-- II. SUBSTRATE (L0 — RAW DATA BUFFER)
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS substrate.raw_clan_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payload JSONB NOT NULL,
    ingested_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
COMMENT ON TABLE substrate.raw_clan_members IS 'L0 Buffer: Raw JSON snapshot of the clan roster.';

CREATE TABLE IF NOT EXISTS substrate.raw_river_race (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payload JSONB NOT NULL,
    ingested_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
COMMENT ON TABLE substrate.raw_river_race IS 'L0 Buffer: Raw JSON snapshot of the current war race.';

-- -------------------------------------------------------------------------
-- III. DRIVERS (L2 — RELATIONAL DNA)
-- -------------------------------------------------------------------------

-- 1. MEMBERS (The Active Roster)
CREATE TABLE IF NOT EXISTS drivers.members (
    tag TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    role TEXT,
    exp_level INTEGER,
    trophies INTEGER DEFAULT 0,
    donations INTEGER DEFAULT 0,
    donations_received INTEGER DEFAULT 0,
    war_wins INTEGER DEFAULT 0,
    joined_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_seen_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_ingested_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_active BOOLEAN DEFAULT TRUE
);
COMMENT ON TABLE drivers.members IS 'L2 Drivers: The authoritative source for member telemetry.';

-- 2. WAR ACTIVITY (The 4-Day Window)
CREATE TABLE IF NOT EXISTS drivers.war_activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_tag TEXT REFERENCES drivers.members(tag) ON DELETE CASCADE,
    week_id TEXT NOT NULL,
    decks_used INTEGER DEFAULT 0,
    fame INTEGER DEFAULT 0,
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
COMMENT ON TABLE drivers.war_activity IS 'L2 Drivers: Recent war day activity logs.';

-- 3. WAR HISTORY (The Infinite Career Ledger)
CREATE TABLE IF NOT EXISTS drivers.war_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag TEXT REFERENCES drivers.members(tag) ON DELETE CASCADE,
    week_id TEXT NOT NULL,
    fame INTEGER DEFAULT 0,
    rank INTEGER,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(tag, week_id)
);
COMMENT ON TABLE drivers.war_history IS 'L2 Drivers: Infinite historical war archive.';

-- -------------------------------------------------------------------------
-- IV. THE SHREDDERS (L0 -> L2 TRANSFORMERS)
-- -------------------------------------------------------------------------

-- 1. MEMBER SHREDDER
CREATE OR REPLACE FUNCTION substrate.shred_clan_members()
RETURNS TRIGGER AS $$
DECLARE
    v_member RECORD;
    v_items JSONB;
BEGIN
    -- Polymorphic detection (RoyaleAPI can return {"items":[]} or [])
    v_items := CASE 
        WHEN jsonb_typeof(NEW.payload) = 'array' THEN NEW.payload
        WHEN NEW.payload ? 'items' AND jsonb_typeof(NEW.payload->'items') = 'array' THEN NEW.payload->'items'
        ELSE NULL
    END;

    IF v_items IS NULL THEN RETURN NEW; END IF;

    -- Deactivate missing residents
    UPDATE drivers.members 
    SET is_active = FALSE 
    WHERE tag NOT IN (SELECT x.tag FROM jsonb_to_recordset(v_items) AS x(tag TEXT));

    -- Upsert active residents
    FOR v_member IN 
        SELECT * FROM jsonb_to_recordset(v_items) AS x(
            tag TEXT, name TEXT, role TEXT, expLevel INTEGER, 
            trophies INTEGER, donations INTEGER, donationsReceived INTEGER
        )
    LOOP
        INSERT INTO drivers.members (
            tag, name, role, exp_level, trophies,
            donations, donations_received, last_ingested_at, is_active
        )
        VALUES (
            v_member.tag, v_member.name, v_member.role, v_member.expLevel, v_member.trophies,
            COALESCE(v_member.donations, 0), COALESCE(v_member.donationsReceived, 0), NOW(), TRUE
        )
        ON CONFLICT (tag) DO UPDATE SET
            name = EXCLUDED.name,
            role = EXCLUDED.role,
            exp_level = EXCLUDED.exp_level,
            trophies = EXCLUDED.trophies,
            donations = EXCLUDED.donations,
            donations_received = EXCLUDED.donations_received,
            last_ingested_at = EXCLUDED.last_ingested_at,
            is_active = TRUE;
    END LOOP;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 2. RIVER RACE SHREDDER
CREATE OR REPLACE FUNCTION substrate.shred_river_race()
RETURNS TRIGGER AS $$
DECLARE
    v_participant RECORD;
    v_week_id TEXT;
BEGIN
    v_week_id := NEW.payload->>'sectionIndex'; -- Usually represents the week shard

    FOR v_participant IN 
        SELECT * FROM jsonb_to_recordset(NEW.payload->'clan'->'participants') AS x(
            tag TEXT, name TEXT, fame INTEGER, decksUsed INTEGER
        )
    LOOP
        INSERT INTO drivers.war_activity (member_tag, week_id, fame, decks_used)
        VALUES (v_participant.tag, v_week_id, v_participant.fame, v_participant.decksUsed)
        ON CONFLICT DO NOTHING; -- Activity is additive, handled by ingest strategy
    END LOOP;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- -------------------------------------------------------------------------
-- V. SCORING KERNEL (L3 — BUSINESS INTELLIGENCE)
-- -------------------------------------------------------------------------

CREATE OR REPLACE VIEW features.scoring_view AS
WITH base_stats AS (
    -- CALCULATE: Core telemetry denominators
    SELECT 
        m.tag,
        m.name,
        m.trophies,
        m.donations,
        m.joined_at,
        m.last_seen_at,
        m.war_wins,
        GREATEST(0, EXTRACT(EPOCH FROM (NOW() - m.last_seen_at)) / 86400.0) AS days_inactive,
        GREATEST(0, EXTRACT(EPOCH FROM (NOW() - m.joined_at)) / 86400.0) AS tenure_days,
        
        -- AGGREGATE: Current War Performance
        COALESCE(
            (SELECT fame FROM drivers.war_activity WHERE member_tag = m.tag ORDER BY recorded_at DESC LIMIT 1), 
            0
        ) AS current_fame,
        
        -- AGGREGATE: Historical War Averages
        COALESCE(
            (SELECT AVG(fame) FROM drivers.war_activity WHERE member_tag = m.tag), 
            0
        ) AS avg_fame,
        
        -- AGGREGATE: Participation Rate
        COALESCE(
            (SELECT (AVG(decks_used) / 4.0) * 100.0 FROM drivers.war_activity WHERE member_tag = m.tag), 
            0
        ) AS war_rate
    FROM drivers.members m
    WHERE m.is_active = TRUE
),
raw_calculations AS (
    -- CALCULATE: The mathematical foundations
    SELECT 
        *,
        -- RPeS: Raw Performance Score (The unscaled merit)
        ROUND(
            (current_fame * 3.0) +    -- w.FAME
            (avg_fame * 15.0) +       -- w.AVG_FAME
            (donations * 100.0) +     -- w.DONATION
            (trophies * 0.1) +        -- w.TROPHY
            (war_rate * 150.0)        -- w.WAR_RATE
        ) AS raw_performance_score,

        -- RPoS: Raw Potential Score (The career foundation)
        (
            (trophies * 1.0) +        -- hh.TROPHY
            (donations * 0.1) +       -- hh.DON
            ((war_wins + 500) * 20.0) -- hh.WAR_WINS + Career Active Bonus
        ) AS raw_potential_score,

        -- DECAY: Inactivity Penalty (8% daily after Day 4)
        POWER(1.0 - 0.08, GREATEST(0, days_inactive - 4.0)) AS decay_multiplier
    FROM base_stats
),
clinical_layer AS (
    -- CALCULATE: Heritage and Total Weighted Result
    SELECT 
        *,
        -- HERITAGE BLESSING: Quadratic protection for new recruits (14-day window)
        CASE 
            WHEN tenure_days < 14.0 
            THEN (raw_potential_score * POWER((14.0 - tenure_days) / 14.0, 2)) / 5.0
            ELSE 0 
        END AS heritage_bonus,
        
        -- INTERMEDIATE: The weighted sum before final normalization
        (raw_performance_score * decay_multiplier) AS decayed_score
    FROM raw_calculations
)
SELECT 
    *,
    -- PeS: Performance Score (Normalized to 100% relative to the current elite)
    CASE 
        WHEN MAX(decayed_score + heritage_bonus) OVER () > 0 
        THEN ROUND(((decayed_score + heritage_bonus) / MAX(decayed_score + heritage_bonus) OVER ()) * 100.0)
        ELSE 0 
    END AS performance_score
FROM clinical_layer;

-- -------------------------------------------------------------------------
-- VI. PUBLIC INTERFACE (L5 — CONTROL VIEW)
-- -------------------------------------------------------------------------

CREATE OR REPLACE VIEW features.roster_view AS
SELECT 
    m.tag,
    m.name,
    m.role,
    m.exp_level,
    m.trophies,
    m.donations,
    s.raw_performance_score,
    s.performance_score,
    m.last_seen_at,
    CASE 
        WHEN s.days_inactive * 24 * 60 < 60 THEN 'Now'
        WHEN s.days_inactive * 24 < 1 THEN (s.days_inactive * 24 * 60)::INT || 'm'
        WHEN s.days_inactive < 1 THEN (s.days_inactive * 24)::INT || 'h'
        ELSE s.days_inactive::INT || 'd'
    END AS tenure_label,
    ROUND(s.heritage_bonus) AS visibility_boost
FROM drivers.members m
LEFT JOIN features.scoring_view s ON m.tag = s.tag
WHERE m.is_active = TRUE
ORDER BY s.raw_performance_score DESC, s.performance_score DESC;

-- -------------------------------------------------------------------------
-- VII. SECURITY & PERMISSIONS
-- -------------------------------------------------------------------------
GRANT USAGE ON SCHEMA substrate, drivers, features TO anon, authenticated;
GRANT SELECT ON ALL TABLES IN SCHEMA features TO anon, authenticated;
