-- SPDX-License-Identifier: GPL-3.0-only
-- Copyright (C) 2026 AlbiDR

/*
============================================================================
HEADHUNTER FOUNDATION
----------------------------------------------------------------------------
Implements the relational architecture for the Headhunter system.

L0: Substrate (Raw json arrays from RoyaleAPI)
L2: Drivers (Recruit Pool, Blacklist)
L3: Features (Scoring logic views)
============================================================================
*/

-- -------------------------------------------------------------------------
-- I. L0 SUBSTRATE (RAW LOGS)
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS substrate.raw_scout_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payload JSONB NOT NULL,
    source TEXT NOT NULL CHECK (source IN ('TOURNAMENT', 'SHADOW')),
    ingested_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
COMMENT ON TABLE substrate.raw_scout_logs IS 'L0 Buffer: Raw JSON snapshot of discovered recruits.';

-- -------------------------------------------------------------------------
-- II. L2 DRIVERS (SSoT RECRUIT DATA)
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS drivers.recruits (
    tag TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    trophies INTEGER DEFAULT 0,
    donations INTEGER DEFAULT 0,
    cards INTEGER DEFAULT 0,
    war_wins INTEGER DEFAULT 0,
    found_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_scan TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    raw_score NUMERIC DEFAULT 0.0,
    source TEXT NOT NULL CHECK (source IN ('TOURNAMENT', 'SHADOW')),
    status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'BENCHED', 'INVITED'))
);
COMMENT ON TABLE drivers.recruits IS 'L2 Drivers: Authoritative queue and pool of recruitment candidates.';

CREATE TABLE IF NOT EXISTS drivers.recruit_blacklist (
    tag TEXT PRIMARY KEY,
    raw_score NUMERIC DEFAULT 0.0,
    expiry_date TIMESTAMP WITH TIME ZONE NOT NULL,
    banned_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
COMMENT ON TABLE drivers.recruit_blacklist IS 'L2 Drivers: The dismissal log for candidates (prevents re-fetching).';

-- -------------------------------------------------------------------------
-- III. THE SHREDDERS (L0 -> L2 TRANSFORMERS)
-- -------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION substrate.shred_scout_logs()
RETURNS TRIGGER AS $$
DECLARE
    v_recruit RECORD;
    v_items JSONB;
BEGIN
    v_items := CASE 
        WHEN jsonb_typeof(NEW.payload) = 'array' THEN NEW.payload
        WHEN NEW.payload ? 'items' AND jsonb_typeof(NEW.payload->'items') = 'array' THEN NEW.payload->'items'
        ELSE NULL
    END;

    IF v_items IS NULL THEN RETURN NEW; END IF;

    -- Upsert recruits, skipping any that are already in the blacklist
    FOR v_recruit IN 
        SELECT * FROM jsonb_to_recordset(v_items) AS x(
            tag TEXT, name TEXT, trophies INTEGER, totalDonations INTEGER, donations INTEGER,
            challengeCardsWon INTEGER, cards INTEGER, warDayWins INTEGER, war INTEGER,
            rawScore NUMERIC
        )
    LOOP
        IF NOT EXISTS (SELECT 1 FROM drivers.recruit_blacklist WHERE tag = v_recruit.tag) THEN
            INSERT INTO drivers.recruits (
                tag, name, trophies, donations, cards, war_wins, 
                raw_score, source, status, found_date, last_scan
            )
            VALUES (
                v_recruit.tag, 
                v_recruit.name, 
                COALESCE(v_recruit.trophies, 0),
                COALESCE(v_recruit.totalDonations, v_recruit.donations, 0),
                COALESCE(v_recruit.challengeCardsWon, v_recruit.cards, 0),
                COALESCE(v_recruit.warDayWins, v_recruit.war, 0),
                COALESCE(v_recruit.rawScore, 0.0),
                NEW.source,
                'ACTIVE',
                NOW(),
                NOW()
            )
            ON CONFLICT (tag) DO UPDATE SET
                trophies = EXCLUDED.trophies,
                donations = EXCLUDED.donations,
                cards = EXCLUDED.cards,
                war_wins = EXCLUDED.war_wins,
                raw_score = GREATEST(drivers.recruits.raw_score, EXCLUDED.raw_score),
                last_scan = NOW();
        END IF;
    END LOOP;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_shred_scout_logs ON substrate.raw_scout_logs;
CREATE TRIGGER trg_shred_scout_logs
    AFTER INSERT ON substrate.raw_scout_logs
    FOR EACH ROW
    EXECUTE FUNCTION substrate.shred_scout_logs();

-- -------------------------------------------------------------------------
-- IV. SECURITY & PERMISSIONS
-- -------------------------------------------------------------------------
GRANT SELECT ON ALL TABLES IN SCHEMA drivers TO anon, authenticated;
